name: Manual GitHub Pages Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert readme.md to index.html
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          pandoc readme.md -o index.html

      - name: Create CNAME file
        run: echo 'kgrid.org' > CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .  # Use . if your static files are in the root directory
