name: Manual GitHub Pages Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Create _config.yml
        run: |
          echo "theme: jekyll-theme-cayman" > _config.yml
          echo "baseurl: /koio" >> _config.yml  # Adjust if necessary

      - name: Create CNAME file
        run: |
          echo 'kgrid.org' > CNAME

      - name: Install Jekyll and dependencies
        run: |
          gem install jekyll bundler
          bundle init
          echo "gem 'jekyll-theme-cayman'" >> Gemfile
          bundle install

      - name: Build Jekyll site with trace
        run: |
          bundle exec jekyll build --trace -d ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
